# A sample Gemfile
source "https://rubygems.org"

gem 'rails', '>= 2.3.10', '< 3.0.0'
gem 'rdoc'
gem 'mysql2', "< 0.3.0"

gem "shoulda"
gem 'timecop', '< 0.5.6' # Ruby 1.9
gem "mocha", '!= 0.13.0', '!= 0.13.1'
gem "factory_girl"

gem "active_sql", '1.0', :path => '../../../'
