# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   There is no gem for Windows.  Install mysql.so from RubyForApache.
#   http://rubyforge.org/projects/rubyforapache
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
active_sql_db_login: &active_sql_db_login
  adapter: mysql2
  username: root
  password:
  host: localhost
  encoding: utf8

development:
  <<: *active_sql_db_login
  database: active_sql_development

test:
  <<: *active_sql_db_login
  database: active_sql_test

production:
  <<: *active_sql_db_login
  database: active_sql_development
